name: Update CODEOWNERS

on:
  pull_request:
    types: ['created', 'edited', 'reopened', 'closed', 'synchronize']

jobs:
  update-codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fedeci/add-codeowners-action@v1
        with:
          token: ${{ secrets.FIG_BOT_TOKEN }}
          codeownersPath: '.github/CODEOWNERS'
      
